MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101-GN"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS: # use GN for backbone
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    TRANS_FUNC: "BottleneckWithGN"
    STEM_FUNC: "StemWithGN"
  FPN:
    USE_GN: True # use GN for FPN
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    PRE_NMS_TOP_N_TRAIN: 1000
    POST_NMS_TOP_N_TRAIN: 500
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 500
    FPN_POST_NMS_TOP_N_TEST: 200
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 128
    POSITIVE_FRACTION: 0.25
    NMS: 0.35
    DETECTIONS_PER_IMG: 50
  ROI_BOX_HEAD:
    USE_GN: True # use GN for bbox head
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_MASK_HEAD:
    USE_GN: True # use GN for mask head
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    CONV_LAYERS: (256, 256, 256, 256)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
    DUAL_MODAL: True
  MASK_ON: True
  MASKIOU_ON: True
  PANOPTIC:
    PS_ON: True
    SEM_PATH: "./datasets/leaf-cvppp/semgt"
    ATTENTION_FUSION: True
    SEMANTIC_CONSISTENCE: True
    SEMANTIC_CONSISTENCE_LAMBDA: 1.0
DATASETS:
  TRAIN: ("leaf_cvppp_a1",)
  TEST: ("leaf_cvppp_a1",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # Assume 8 gpus
  BASE_LR: 0.003
  WEIGHT_DECAY: 0.0001
  STEPS: (4800, 6400)
  MAX_ITER: 6400
  IMS_PER_BATCH: 1
  EPOCH_PERIOD: 800
  CHECKPOINT_PERIOD: 100000
TEST:
  IMS_PER_BATCH: 1
INPUT:
  MIN_SIZE_TRAIN: (512,)
  MAX_SIZE_TRAIN: 512
  MAX_SIZE_TEST: 530
  PIXEL_MEAN: [128.0, 128.0, 128.0]
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  VERTICAL_FLIP_PROB_TRAIN: 0.5
